from shop import views
from django.urls import path

urlpatterns = [
    path('', views.index),
    path('contact-us/', views.contact),
    path('about-us/', views.about_us),
    path('account/register/', views.registration),
    path('account/login/', views.login),
    path('account/change-password/', views.forgot_password),
    path('account/logout/', views.logout),
    path('emi-terms/', views.emi),
    path('warranty-policy/', views.warranty),
    path('payment-method/', views.payment_method),
    path('terms-and-conditions/', views.terms_conditions),
    path('refund-policy/', views.return_refund_policy),
    path('privacy/', views.privacy_policy),
    path('offers/', views.offers),
    path('offers/<int:id>/', views.single_offers),
    path('faq/', views.faq),
    path('wishlist/', views.wishlist),
    path('order-history/', views.order_history),
    path('my-account/', views.my_account),
    path('address-book/', views.my_address_book),
    path('cart-list/', views.cart_list),
    path('checkout/', views.checkout),
    path('payment/cancel', views.payment_cancel),
    path('payment/fail', views.payment_fail),
    path('payment/successful', views.payment_successful),
    path('order-success/', views.order_complete),
    path('<str:pro_name>', views.single_product),
    path('<str:cat_name>/', views.products_cat),
    path('<str:cat_name>/<str:sub_name>/', views.sub_products),
    path('<str:cat_name>/<str:sub_name>/<str:sub_sub_name>/', views.sub_sub_products),
    path('subscribe/newsletter', views.insert_newsletter), 
    path('add-to-cart/<int:id>',views.add_to_cart),  
    path('delete-cart/<int:id>',views.delete_to_cart),
    path('add-to-wish/<int:id>',views.add_to_wish),  
    path('delete-wish/<int:id>',views.delete_to_wish),
]
