# Generated by Django 2.0.3 on 2020-02-20 12:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200217_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='pinterest',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='com_details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
