# Generated by Django 2.0.3 on 2020-02-27 12:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200220_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='thumbnail_image')),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Products')),
            ],
            options={
                'verbose_name': 'Offer Product',
                'verbose_name_plural': 'Offer Products',
            },
        ),
        migrations.CreateModel(
            name='SeoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_meta_title', models.TextField(blank=True)),
                ('index_meta_description', models.TextField(blank=True)),
                ('index_meta_keywords', models.TextField(blank=True)),
                ('contact_us_title', models.TextField(blank=True)),
                ('contact_us_description', models.TextField(blank=True)),
                ('contact_us_keywords', models.TextField(blank=True)),
                ('offer_product_title', models.TextField(blank=True)),
                ('offer_product_description', models.TextField(blank=True)),
                ('offer_product_keywords', models.TextField(blank=True)),
                ('faq_title', models.TextField(blank=True)),
                ('faq_description', models.TextField(blank=True)),
                ('faq_keywords', models.TextField(blank=True)),
                ('login_title', models.TextField(blank=True)),
                ('login_description', models.TextField(blank=True)),
                ('login_keywords', models.TextField(blank=True)),
                ('reg_title', models.TextField(blank=True)),
                ('reg_description', models.TextField(blank=True)),
                ('reg_keywords', models.TextField(blank=True)),
                ('fogt_title', models.TextField(blank=True)),
                ('fogt_description', models.TextField(blank=True)),
                ('fogt_keywords', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seo Content',
                'verbose_name_plural': 'Seo Contentes',
            },
        ),
    ]
