# Generated by Django 2.0.3 on 2020-02-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_offerproduct_seocontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('qt_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('cart_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products')),
            ],
            options={
                'verbose_name': 'Add To Cart',
                'verbose_name_plural': 'Cart List',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('total_price', models.IntegerField(default=0)),
                ('wish_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
    ]
