# Generated by Django 2.0.3 on 2020-03-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_addtocart_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='validation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
