# Generated by Django 2.0.3 on 2020-03-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_offerproduct_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='glg_map',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email_address',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
