# Generated by Django 2.0.3 on 2020-03-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_addressbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='addressbook',
            name='user_mobile',
        ),
        migrations.RemoveField(
            model_name='addressbook',
            name='user_name',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.UserRegistration'),
            preserve_default=False,
        ),
    ]
