# Generated by Django 2.0.3 on 2020-03-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200312_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sliderinfo',
            name='title2',
        ),
    ]
