# Generated by Django 2.0.3 on 2020-03-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200315_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=80)),
                ('mobile', models.CharField(max_length=16)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(default=0)),
                ('price_after_charge', models.FloatField(default=0)),
                ('invoice_no', models.CharField(max_length=60, unique=True)),
                ('aamar_pay_txd_id', models.CharField(max_length=60, unique=True)),
                ('zip_code', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales Histories',
            },
        ),
    ]
