# Generated by Django 2.0.3 on 2020-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_saleshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleshistory',
            name='aamar_pay_txd_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
